---
- file:
    state: directory
    path: /opt/nomad
    
- file:
    state: directory
    path: /opt/nomad/config
    
- file:
    state: directory
    path: /opt/nomad/config/ssl
    
- file:
    state: directory
    path: /opt/nomad/data
    
- name: copy rootca
  copy:
    dest: "/opt/nomad/config/ssl/ca.cert.pem"
    # src: "../../ca/ca/certs/ca.cert.pem"
    src: ../../ca/ca/intermediate/certs/intermediate.cert.chain.pem
    owner: root
    group: wheel
    mode: "u=rwxrxrx"
    
- name: copy nomad server key
  copy:
    dest: "/opt/nomad/config/ssl/{{ inventory_hostname }}.key"
    src: "../../ca/outputs/{{ inventory_hostname }}/{{ inventory_hostname }}.key"
    owner: root
    group: wheel
    mode: "u=rwxrxrx"
    
- name: copy nomad server certificate
  copy:
    dest: "/opt/nomad/config/ssl/{{ inventory_hostname }}.crt"
    src: "../../ca/outputs/{{ inventory_hostname }}/{{ inventory_hostname }}.crt"
    owner: root
    group: wheel
    mode: "u=rwxrxrx"

- unarchive:
    remote_src: yes
    dest: /usr/bin
    src: https://releases.hashicorp.com/nomad/{{ hashicorp_nomad_version }}/nomad_{{ hashicorp_nomad_version }}_linux_amd64.zip
    owner: root
    group: wheel
    mode: 0755

- template:
    dest: /opt/nomad/config/nomad.hcl
    src: "nomad.hcl.j2"
    owner: root
    group: wheel
    mode: "u=rwx,g=r"
  notify: 
    - restart nomad
    - reload nomad service

- template:
    dest: /etc/systemd/system/nomad.service
    src: "nomad.service.j2"
    owner: root
    group: wheel
    mode: "u=rwx,g=r"
  notify: 
    - restart nomad
    - reload nomad service

- service:
    name: nomad
    state: started
    enabled: true