---
- hosts: "all"
  remote_user: root
  become: yes
  tasks:
    - name: install python-pip package
      yum:
        name: python-pip
        state: latest
        update_cache: yes

    - name: update pip
      pip: 
        name: pip

    - name: install python docker-py
      pip: 
        name: docker-py

    - name: "install docker-compose"
      get_url:
        url: https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "0755"